### ISSUE TITLE
World light preview

### ISSUE THREAD

**Issue by Ch3st3r2000** [hampusborgos/rme#138]
Hi, just asking if there is possibility to implent something like time of day mode? To see how the map would look at night, how would look light effects like lamps, torches etc underground. Something like ingame.
I know that i can just start the server go there and see but this feature would save a lot of time.. So like i said before is that possible? if not now, maybe in future?

**Comment by Kamenuvol** [comment]
I agree and think it is possible. And there is the problem to know what the player will see, if on that sqm he will see the mou tain above, how many levels of it, or only his floor

**Comment by Ch3st3r2000** [comment]
Well, if that feature would be toggleable by ON/OFF, i think that only selected floor (or +1, 0 and -1) should have layer of effects visible. Why only current floor? because it would avoid some bugs like overlap of light layers.

**Comment by Mignari** [comment]
For now there are no plans to implement lights

**Comment by hjnilsson** [comment]
It's certainly possible, but it is quite difficult to imitate the lightning behaviour in the Tibia Client. If this is every implemented, I would recommend looking at the YATC code for it: https://github.com/opentibia/yatc/blob/master/engine.cpp#L386

**Comment by totolol123** [comment]
Important feature indeed and would worth the effort.
