### ISSUE TITLE
Creature addons issue

### ISSUE THREAD

**Issue by yamaken93** [hampusborgos/rme#275]
![image](https://user-images.githubusercontent.com/1008865/61406250-db186e80-a8b1-11e9-973c-fd9d16b7e0de.png)
It does not daw the nomad's outfit addons. How difficult is to fix this in RME?

**Comment by Sickness-chan** [comment]
RME does not just draw a nomad's addons, it does not draw any outfit addons. I've looked into this a while ago, but I got to the point where I only had the drawing left to add, but I didn't understand the structure of how the outfits are parsed. I believe the drawing happens here https://github.com/hjnilsson/rme/blob/272c0a987fa9d667cda81ad1de078a8a45f552ba/source/graphics.cpp#L919

When you import a creature's XML file, the addons attribute isn't parsed correctly either and has to be fixed.

I believe you could look at https://github.com/edubart/otclient/blob/425b3bfdda3ab44140ea334c41c8267a036c9cfd/src/client/creature.cpp#L105-#L194 to figure out how to get the addons into GameSprite::getHardwareID

**Comment by hjnilsson** [comment]
@Sickness-chan The code you linked has nothing to do with addons, rather, addons are entirely separate sprites, that needs to be drawn after the main sprite.

So in metacode:

    drawOutfit(....) // uses getHardwareId
    for (addons on outfit)
        drawAddon(...) // Probably also uses getHardwareId, but with a different sprite

**Comment by yamaken93** [comment]
Fixed by me #357
