### ISSUE TITLE
Convert maps to different otb

### ISSUE THREAD

**Issue by omarcopires** [hampusborgos/rme#328]
One of the big problems today is the wide variety of otb spread over the internet and most of them are in the same version.
I've been thinking of a way to convert maps, first saving as a client id, and later saving as a serverid.
In a previous issue I found how to save with clientid, but I still haven't been able to open it as clientid and save it as serverid, if anyone has any idea how to do it, I would be grateful for the help.
I believe this is getting very confusing, but I think it is readable.

**Comment by peonso** [comment]
I think you couldn't make such tool with https://github.com/Inconcessus/OTBM2JSON, something like that https://otland.net/threads/convert-any-map-to-7-6.259410/ but instead of using a custom data you use your items.otb data to convert a map from client id to the items.otb server data.
