### ISSUE TITLE
compiling on macOS issue

### ISSUE THREAD

**Issue by Moromizatos** [hampusborgos/rme#329]
.../rme/source/gui.cpp:1186:106: error: no member named 'FromDIP' in 'MainFrame'
  ...= newd WelcomeDialog(__W_RME_APPLICATION_NAME__, "Version " + __W_RME_VERSION__, _root_->FromDIP(wxSize(...

**Comment by mtstickney** [comment]
I can't speak to your particular setup, but this error is probably that you're building against an older version of wxWidgets (pre-3.1). The FromDIP method was added in wxWidgets 3.1, and rme 3.7 uses it for DPI support, so despite what the readme says it needs wxWidgets >= 3.1.

The 3.6.1 tag built successfully for me with wxWidgets 3.0.5, which is the last version my linux distro actually packages.
