### ISSUE TITLE
Normal Doors = Closed Doors??

### ISSUE THREAD

**Issue by Alkenix** [hampusborgos/rme#363]
Heyho.

I'm using lates TFS 1.3 to map and 10.98 version map in the latest RME 3.7 (tried 3.2 too).
When I place a normal door (for example ID 6252) it ends up as an closed one in game.
https://otland.net/threads/tfs-1-3-buggy-doors.277428/

**Comment by BahamutxD** [comment]
Use 6253 instead. Most (all?) normal doors have a locked version - you can check that by going to tfs/data/global.lua

`lockedDoors = {
	1209, 1212, 1231, 1234, 1249, 1252, 3535, 3544, 4913, 4916, 5098, 5107, 5116, 5125, 5134, 5137, 5140,
	5143, 5278, 5281, 5732, 5735, 6192, 6195, 6249, **6252**, 6891, 6900, 7033, 7042, 8541, 8544, 9165, 9168,
	9267, 9270, 10268, 10271, 10468, 10477, 10775, 10784, 12092, 12099, 12188, 12197, 19840, 19849, 19980,
	19989, 20273, 20282
}`

You can also check the name for it under items.xml

`	<item id="6252" article="a" name="closed door" editorsuffix=" (Locked)">
		<attribute key="type" value="door" />
		<attribute key="blockprojectile" value="1" />
		<attribute key="description" value="It is locked." />
	</item>
	<item id="6253" article="a" name="closed door">
		<attribute key="type" value="door" />
		<attribute key="blockprojectile" value="1" />
	</item>`

**Comment by Alkenix** [comment]
I won't start RAWing Doors.. This would be a huge backstep for RME.
But if RME has no bug here, it's an TFS 1.3 bug. Gonna check this out.

**Comment by Alkenix** [comment]
Normal placed stone wall door ID, after your fix (done it local for myself too): 6253
- Good thing: No more switching when try to open.
- Still problem: Locked.

10:28 You see a closed door.
Item ID: 6253
Position: 492, 513, 7
10:29 It is locked.

This happens to all doors that are auto placed by tool in rme (placed them ALL new). ^^
10:29 You see a closed door.
Item ID: 1210
Position: 496, 522, 6
10:29 It is locked.

**Comment by Alkenix** [comment]
Did your changes to test and it's working. Thanks! 👍
